tools:
  jdk: 1.8
  maven: 3.3.9
  sonarscanner: 3.0.3.778

triggers:
   push: disabled
   pr: disabled
   
envs:
   global:
      variables:
        oneops.organization: boppa
        oneops.assembly: GAIv1-REST
        oneops.environment: $Environment
        oneops.platform: GAI-Restful
        oneops.component: artifact-app
flows:
  default(ui startCICD):
    - call: build
    - call: runSonar
    - call: runUploadToRepo
    # - call: runDeployment
    - call: triggerDeploymentValidation
   
  
  build: 
    - mvn -f ./pom.xml clean install 
    #-Dmaven.test.skip=true
     
  runSonar(ui runSonar): 
    - sonar("Sonar"): sonar-scanner -Dproject.settings=sonar-project.properties
  
  runUploadToRepo(ui runUploadToRepo):
    - mvn -f ./pom.xml deploy -Dmaven.test.skip=true
    
  runDeployment(ui runDeployment):
    - exposeVars(maven)
    - oneops.transitionVariableUpdate(variables =  { appVersion = ${MAVEN_VERSION} })
    - oneops.environmentCommitAndDeploy(platform = GAI-Restful, deployAllPlatforms = false )

  triggerDeploymentValidation(ui triggerDeploymentValidation):
    - sleep 5m